# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("routing_priority", models.PositiveIntegerField(default=100)),
                ("supported_categories", models.JSONField(blank=True, default=list)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "assignment_strategy",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("ROUND_ROBIN", "Round Robin"),
                            ("LEAST_ACTIVE", "Least Active"),
                            ("RANDOM", "Random"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "max_active_per_agent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Overrides an agent’s own capacity for this queue only, when set.",
                        null=True,
                    ),
                ),
                ("round_robin_cursor", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fallback_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_for",
                        to="queues.queue",
                    ),
                ),
            ],
            options={
                "ordering": ["routing_priority", "name"],
            },
        ),
    ]
