# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("queues", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queue",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queues",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="queue",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queues",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="queue",
            unique_together={("workspace", "name")},
        ),
    ]
