# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar_url_user_display_name_user_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatorpresence",
            name="max_capacity",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="operatorpresence",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("AWAY", "Away"),
                    ("BUSY", "Busy"),
                    ("DO_NOT_DISTURB", "Do Not Disturb"),
                    ("OFFLINE", "Offline"),
                ],
                default="OFFLINE",
                max_length=20,
            ),
        ),
    ]
