# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
        ("collaboration", "0001_initial"),
        (
            "conversations",
            "0005_assignment_new_team_assignment_previous_assignee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quickreply",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quick_replies",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="quickreply",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_replies_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quickreply",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quick_replies",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentions_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="mentioned_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="conversations.message",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mention",
            unique_together={("note", "mentioned_user")},
        ),
    ]
