# Generated by Django 4.2.7 on 2026-08-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "conversations",
            "0005_assignment_new_team_assignment_previous_assignee_and_more",
        ),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("CONVERSATION_CREATED", "Conversation created"),
                            ("CONVERSATION_QUEUED", "Conversation queued"),
                            ("CONVERSATION_ASSIGNED", "Conversation assigned"),
                            ("CONVERSATION_UNASSIGNED", "Conversation unassigned"),
                            ("CONVERSATION_TRANSFERRED", "Conversation transferred"),
                            ("CONVERSATION_ESCALATED", "Conversation escalated"),
                            ("CONVERSATION_PRIORITY_CHANGED", "Priority changed"),
                            ("CONVERSATION_STATUS_CHANGED", "Status changed"),
                            ("CUSTOMER_MESSAGE_CREATED", "Customer message created"),
                            ("OPERATOR_MESSAGE_CREATED", "Operator message created"),
                            ("INTERNAL_NOTE_CREATED", "Internal note created"),
                            ("SLA_APPROACHING", "SLA approaching"),
                            ("SLA_BREACHED", "SLA breached"),
                            ("RATING_SUBMITTED", "Rating submitted"),
                            ("CONVERSATION_RESOLVED", "Conversation resolved"),
                            ("CONVERSATION_CLOSED", "Conversation closed"),
                            ("CONVERSATION_REOPENED", "Conversation reopened"),
                            ("SCHEDULED_TIME_REACHED", "Scheduled time reached"),
                        ],
                        max_length=40,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("priority", models.IntegerField(default=100)),
                ("stop_processing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_rules_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rule_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("trigger_type", models.CharField(max_length=40)),
                ("event_id", models.UUIDField()),
                ("correlation_id", models.UUIDField()),
                ("depth", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched"),
                            ("NOT_MATCHED", "Not matched"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIALLY_SUCCEEDED", "Partially succeeded"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("SKIPPED_LOOP", "Skipped (loop protection)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("condition_result", models.BooleanField(blank=True, null=True)),
                (
                    "actor_type",
                    models.CharField(blank=True, default="SYSTEM", max_length=20),
                ),
                ("actor_id", models.CharField(blank=True, default="", max_length=64)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True, default="")),
                ("is_simulation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_executions",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="automations.automationrule",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=40)),
                ("correlation_id", models.UUIDField()),
                ("depth", models.PositiveIntegerField(default=0)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_events",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutomationActionExecution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action_index", models.PositiveIntegerField()),
                ("action_type", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=15,
                    ),
                ),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                (
                    "affected_object_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "affected_object_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("error_summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_executions",
                        to="automations.automationexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["action_index"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_definition", models.JSONField()),
                ("correlation_id", models.UUIDField()),
                ("depth", models.PositiveIntegerField(default=0)),
                ("execute_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("last_error", models.TextField(blank=True, default="")),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, default="", max_length=64)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_actions",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_actions",
                        to="automations.automationrule",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_actions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["execute_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "execute_at"],
                        name="autosched_status_time_idx",
                    ),
                    models.Index(
                        fields=["workspace", "status"], name="autosched_workspace_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["workspace", "trigger_type", "is_active", "priority"],
                name="autorule_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["workspace", "created_at"], name="autoexec_workspace_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["correlation_id"], name="autoexec_correlation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["rule", "correlation_id"], name="autoexec_rule_corr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationevent",
            index=models.Index(
                fields=["correlation_id"], name="autoevent_correlation_idx"
            ),
        ),
    ]
