# Generated by Django 4.2.7 on 2026-08-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="automationrule",
            options={"ordering": ["priority", "created_at", "id"]},
        ),
    ]
