# Generated by Django 4.2.7 on 2026-08-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        (
            "conversations",
            "0005_assignment_new_team_assignment_previous_assignee_and_more",
        ),
        ("automations", "0002_alter_automationrule_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationCorrelationCounter",
            fields=[
                ("correlation_id", models.UUIDField(primary_key=True, serialize=False)),
                ("actions_reserved", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_correlation_counters",
                        to="workspaces.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutomationActionSideEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("action_type", models.CharField(max_length=40)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                (
                    "affected_object_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "affected_object_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_action_side_effects",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_action_side_effects",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "reserved_at"],
                        name="autoactsfx_workspace_idx",
                    )
                ],
            },
        ),
    ]
