# Generated by Django 4.2.7 on 2026-08-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        ("automations", "0003_automationcorrelationcounter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationActionSlotReservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("correlation_id", models.UUIDField()),
                ("reservation_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_action_slot_reservations",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["correlation_id"], name="autoslotrsv_correlation_idx"
                    )
                ],
            },
        ),
    ]
