# Generated by Django 4.2.7 on 2026-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CONVERSATION_ASSIGNED", "Conversation assigned"),
                    ("CONVERSATION_TRANSFERRED", "Conversation transferred"),
                    ("MENTIONED", "Mentioned"),
                    ("CUSTOMER_REPLIED", "Customer replied"),
                    ("SLA_APPROACHING", "SLA approaching"),
                    ("SLA_BREACHED", "SLA breached"),
                    ("ESCALATION_RECEIVED", "Escalation received"),
                    ("AUTOMATION_TRIGGERED", "Automation notification"),
                ],
                max_length=40,
            ),
        ),
    ]
