# Generated by Django 4.2.7 on 2026-08-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_category_conversation_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conversation",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="attachments/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("VOICE", "Voice"),
                    ("PRODUCT", "Product"),
                    ("RATING_REQUEST", "Rating Request"),
                    ("RATING", "Rating"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
