# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_conversation_notes_conversation_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorityChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("QUEUE_DEFAULT", "Queue default"),
                            ("SLA_BREACH", "SLA breach"),
                            ("ESCALATION", "Escalation"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="action",
            field=models.CharField(
                choices=[
                    ("ASSIGN", "Assign"),
                    ("REASSIGN", "Reassign"),
                    ("CLAIM", "Claim"),
                    ("TRANSFER", "Transfer"),
                    ("UNASSIGN", "Unassign"),
                    ("RETURN_TO_QUEUE", "Return to queue"),
                    ("AUTO_ASSIGN", "Automatic assignment"),
                    ("ESCALATE", "Escalate"),
                ],
                default="ASSIGN",
                max_length=20,
            ),
        ),
    ]
