# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("queues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversations", "0004_prioritychange_assignment_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="new_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="previous_assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="previous_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conversation",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("NORMAL", "Normal"),
                    ("HIGH", "High"),
                    ("URGENT", "Urgent"),
                ],
                default="NORMAL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="queue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="queues.queue",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("VOICE", "Voice"),
                    ("PRODUCT", "Product"),
                    ("RATING_REQUEST", "Rating Request"),
                    ("RATING", "Rating"),
                    ("INTERNAL_NOTE", "Internal Note"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prioritychange",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prioritychange",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priority_changes",
                to="conversations.conversation",
            ),
        ),
    ]
