# Generated by Django 4.2.7 on 2026-08-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conversations",
            "0005_assignment_new_team_assignment_previous_assignee_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("VOICE", "Voice"),
                    ("PRODUCT", "Product"),
                    ("RATING_REQUEST", "Rating Request"),
                    ("RATING", "Rating"),
                    ("INTERNAL_NOTE", "Internal Note"),
                    ("ARTICLE", "Knowledge Base Article"),
                ],
                default="TEXT",
                max_length=20,
            ),
        ),
    ]
