# Generated by Django 4.2.7 on 2026-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
