# Generated by Django 4.2.7 on 2026-08-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_context", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
