# Generated by Django 4.2.7 on 2026-08-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchedulerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("last_run_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        max_length=10,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=500)),
            ],
        ),
    ]
