# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConversationSLA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "first_response_target_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "next_response_target_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "resolution_target_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("first_response_due_at", models.DateTimeField(blank=True, null=True)),
                ("next_response_due_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_due_at", models.DateTimeField(blank=True, null=True)),
                ("first_responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_response_breached_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "next_response_breached_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("resolution_breached_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_response_approaching_notified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "next_response_approaching_notified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "resolution_approaching_notified_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_working",
                    models.BooleanField(
                        default=False,
                        help_text="True = exceptional working day; False = closure/holiday.",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="WorkingInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_intervals",
                        to="sla.businesscalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        help_text="Blank applies to every priority.",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("first_response_target_minutes", models.PositiveIntegerField()),
                (
                    "next_response_target_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("resolution_target_minutes", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank means the targets are wall-clock (24/7), not business-hours-aware.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sla_policies",
                        to="sla.businesscalendar",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_policies",
                        to="queues.queue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SLA policies",
                "ordering": ["-created_at"],
            },
        ),
    ]
