# Generated by Django 4.2.7 on 2026-08-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("workspaces", "0001_initial"),
        ("sla", "0001_initial"),
        (
            "conversations",
            "0005_assignment_new_team_assignment_previous_assignee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="slapolicy",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_policies",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla_policies",
                to="workspaces.workspace",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="sla.businesscalendar",
            ),
        ),
        migrations.AddField(
            model_name="conversationsla",
            name="conversation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sla",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationsla",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sla.slapolicy",
            ),
        ),
        migrations.AddField(
            model_name="businesscalendar",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_calendars",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("calendar", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="businesscalendar",
            unique_together={("workspace", "name")},
        ),
    ]
