# Generated by Django 4.2.7 on 2026-08-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sla", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="holiday",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
