# Generated by Django 4.2.7 on 2026-08-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversations", "0006_alter_message_message_type"),
        ("teams", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Macro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private (owner only)"),
                            ("TEAM", "Team"),
                            ("WORKSPACE", "Workspace"),
                        ],
                        default="WORKSPACE",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("shortcut", models.CharField(blank=True, default="", max_length=50)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="macros_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_macros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macros",
                        to="teams.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="macros_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macros",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MacroExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIALLY_SUCCEEDED", "Partially succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("actions_snapshot", models.JSONField(blank=True, default=list)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="macro_executions",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="macro_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "macro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="macros.macro",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macro_executions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MacroActionExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_index", models.PositiveIntegerField()),
                ("action_type", models.CharField(max_length=50)),
                ("params_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "affected_object_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "affected_object_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_executions",
                        to="macros.macroexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["action_index"],
            },
        ),
        migrations.AddIndex(
            model_name="macroexecution",
            index=models.Index(
                fields=["workspace", "macro"], name="macroexec_ws_macro_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="macroexecution",
            index=models.Index(
                fields=["workspace", "conversation"], name="macroexec_ws_conv_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="macroexecution",
            unique_together={("workspace", "idempotency_key")},
        ),
        migrations.AlterUniqueTogether(
            name="macroactionexecution",
            unique_together={("execution", "action_index")},
        ),
        migrations.AddIndex(
            model_name="macro",
            index=models.Index(
                fields=["workspace", "is_active", "visibility"],
                name="macro_ws_active_vis_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="macro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("shortcut", ""), _negated=True),
                fields=("workspace", "shortcut"),
                name="macro_shortcut_unique_when_set",
            ),
        ),
    ]
